// ===== Dalnic Premier League — league & squad data =====
// GENERATED by update-kit/generate-dalnic-data.js — edit the CSVs, not this file.
var DALNIC = {
 "ATTRS": [
  "pace",
  "technique",
  "passing",
  "finishing",
  "tackling",
  "heading",
  "strength",
  "stamina",
  "handling",
  "reflexes"
 ],
 "clubs": [
  {
   "name": "Dynamo Bresno",
   "abbr": "DYN",
   "str": 73,
   "style": "Principality-backed giants",
   "color": "#1b2a4a",
   "squad": [
    {
     "name": "Stefan Marusic",
     "num": 1,
     "pos": "GK",
     "qual": 15,
     "att": {
      "pace": 11,
      "technique": 15,
      "passing": 14,
      "finishing": 9,
      "tackling": 11,
      "heading": 17,
      "strength": 18,
      "stamina": 14,
      "handling": 19,
      "reflexes": 18
     }
    },
    {
     "name": "Benno Kreutzer",
     "num": 21,
     "pos": "GK",
     "qual": 12,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 10,
      "finishing": 6,
      "tackling": 7,
      "heading": 12,
      "strength": 14,
      "stamina": 13,
      "handling": 17,
      "reflexes": 18
     }
    },
    {
     "name": "Filip Novak",
     "num": 13,
     "pos": "GK",
     "qual": 11,
     "att": {
      "pace": 9,
      "technique": 13,
      "passing": 8,
      "finishing": 3,
      "tackling": 6,
      "heading": 12,
      "strength": 13,
      "stamina": 13,
      "handling": 16,
      "reflexes": 15
     }
    },
    {
     "name": "Marco Signorelli",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 14,
      "passing": 14,
      "finishing": 10,
      "tackling": 14,
      "heading": 11,
      "strength": 12,
      "stamina": 15,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Andriy Melnyk",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 17,
      "technique": 13,
      "passing": 17,
      "finishing": 11,
      "tackling": 18,
      "heading": 15,
      "strength": 16,
      "stamina": 16,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Viktor Kosa",
     "num": 5,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 15,
      "technique": 12,
      "passing": 17,
      "finishing": 12,
      "tackling": 20,
      "heading": 20,
      "strength": 19,
      "stamina": 14,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Omar Al-Faraj",
     "num": 4,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 14,
      "finishing": 9,
      "tackling": 19,
      "heading": 20,
      "strength": 19,
      "stamina": 12,
      "handling": 12,
      "reflexes": 15
     }
    },
    {
     "name": "Petar Simic",
     "num": 20,
     "pos": "CB",
     "qual": 11,
     "att": {
      "pace": 9,
      "technique": 8,
      "passing": 12,
      "finishing": 6,
      "tackling": 15,
      "heading": 14,
      "strength": 13,
      "stamina": 11,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Nico Jovanovic",
     "num": 26,
     "pos": "CB",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 8,
      "passing": 9,
      "finishing": 6,
      "tackling": 13,
      "heading": 15,
      "strength": 15,
      "stamina": 12,
      "handling": 10,
      "reflexes": 12
     }
    },
    {
     "name": "Jacek Kowalski",
     "num": 14,
     "pos": "RB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 11,
      "passing": 12,
      "finishing": 8,
      "tackling": 15,
      "heading": 11,
      "strength": 13,
      "stamina": 16,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Andrei Stoica",
     "num": 15,
     "pos": "LB",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 14,
      "finishing": 7,
      "tackling": 13,
      "heading": 9,
      "strength": 13,
      "stamina": 14,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Raul Sebastian",
     "num": 6,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 15,
      "finishing": 11,
      "tackling": 20,
      "heading": 13,
      "strength": 15,
      "stamina": 17,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Emil Kovac",
     "num": 16,
     "pos": "DM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 14,
      "passing": 14,
      "finishing": 10,
      "tackling": 16,
      "heading": 13,
      "strength": 14,
      "stamina": 14,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Stefano Toscano",
     "num": 19,
     "pos": "CM",
     "qual": 15,
     "att": {
      "pace": 17,
      "technique": 20,
      "passing": 20,
      "finishing": 14,
      "tackling": 17,
      "heading": 17,
      "strength": 17,
      "stamina": 18,
      "handling": 14,
      "reflexes": 17
     }
    },
    {
     "name": "Liam Fitzroy",
     "num": 8,
     "pos": "CM",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 17,
      "passing": 18,
      "finishing": 14,
      "tackling": 15,
      "heading": 13,
      "strength": 12,
      "stamina": 16,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Martin Havel",
     "num": 12,
     "pos": "CM",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 17,
      "passing": 16,
      "finishing": 11,
      "tackling": 14,
      "heading": 12,
      "strength": 13,
      "stamina": 16,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Raul Ferreira",
     "num": 35,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 14,
      "finishing": 9,
      "tackling": 12,
      "heading": 12,
      "strength": 10,
      "stamina": 11,
      "handling": 10,
      "reflexes": 12
     }
    },
    {
     "name": "Rico Villalobos",
     "num": 22,
     "pos": "AM",
     "qual": 14,
     "att": {
      "pace": 17,
      "technique": 19,
      "passing": 18,
      "finishing": 15,
      "tackling": 12,
      "heading": 11,
      "strength": 16,
      "stamina": 15,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Kenji Sato",
     "num": 38,
     "pos": "AM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 17,
      "passing": 16,
      "finishing": 16,
      "tackling": 10,
      "heading": 12,
      "strength": 14,
      "stamina": 13,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Farid Karam",
     "num": 7,
     "pos": "RW",
     "qual": 14,
     "att": {
      "pace": 20,
      "technique": 18,
      "passing": 14,
      "finishing": 16,
      "tackling": 13,
      "heading": 13,
      "strength": 15,
      "stamina": 14,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Nico Vanic",
     "num": 11,
     "pos": "LW",
     "qual": 13,
     "att": {
      "pace": 18,
      "technique": 15,
      "passing": 12,
      "finishing": 15,
      "tackling": 10,
      "heading": 10,
      "strength": 11,
      "stamina": 15,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Diego Barros",
     "num": 24,
     "pos": "LW",
     "qual": 12,
     "att": {
      "pace": 20,
      "technique": 15,
      "passing": 12,
      "finishing": 15,
      "tackling": 10,
      "heading": 8,
      "strength": 13,
      "stamina": 13,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Tomas Varga",
     "num": 17,
     "pos": "RW",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 12,
      "finishing": 14,
      "tackling": 10,
      "heading": 10,
      "strength": 10,
      "stamina": 11,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Lucas Brenner",
     "num": 23,
     "pos": "RW",
     "qual": 10,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 9,
      "finishing": 11,
      "tackling": 9,
      "heading": 7,
      "strength": 10,
      "stamina": 11,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Aleksandr Kovalenko",
     "num": 9,
     "pos": "ST",
     "qual": 15,
     "att": {
      "pace": 19,
      "technique": 15,
      "passing": 15,
      "finishing": 20,
      "tackling": 10,
      "heading": 19,
      "strength": 17,
      "stamina": 16,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Luka Petrovic",
     "num": 10,
     "pos": "ST",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 16,
      "passing": 13,
      "finishing": 20,
      "tackling": 10,
      "heading": 17,
      "strength": 17,
      "stamina": 13,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Jean-Luc Martenne",
     "num": 27,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 10,
      "passing": 9,
      "finishing": 16,
      "tackling": 6,
      "heading": 15,
      "strength": 11,
      "stamina": 13,
      "handling": 13,
      "reflexes": 11
     }
    },
    {
     "name": "Emil Jorensen",
     "num": 29,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 12,
      "passing": 10,
      "finishing": 14,
      "tackling": 6,
      "heading": 14,
      "strength": 14,
      "stamina": 10,
      "handling": 11,
      "reflexes": 10
     }
    }
   ]
  },
  {
   "name": "Union Dalnica",
   "abbr": "UND",
   "str": 80,
   "style": "Capital powerhouse",
   "color": "#7a1f2b",
   "squad": [
    {
     "name": "Beni Renke",
     "num": 1,
     "pos": "GK",
     "qual": 16,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 14,
      "finishing": 10,
      "tackling": 12,
      "heading": 17,
      "strength": 19,
      "stamina": 17,
      "handling": 19,
      "reflexes": 20
     }
    },
    {
     "name": "Beni Mraz",
     "num": 13,
     "pos": "GK",
     "qual": 15,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 12,
      "finishing": 7,
      "tackling": 12,
      "heading": 16,
      "strength": 15,
      "stamina": 15,
      "handling": 19,
      "reflexes": 20
     }
    },
    {
     "name": "Hans Sengupta",
     "num": 2,
     "pos": "RB",
     "qual": 15,
     "att": {
      "pace": 17,
      "technique": 15,
      "passing": 18,
      "finishing": 12,
      "tackling": 17,
      "heading": 14,
      "strength": 15,
      "stamina": 18,
      "handling": 14,
      "reflexes": 16
     }
    },
    {
     "name": "Dario Vance",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 16,
      "finishing": 11,
      "tackling": 16,
      "heading": 14,
      "strength": 14,
      "stamina": 18,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Emre Mironov",
     "num": 5,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 15,
      "finishing": 9,
      "tackling": 19,
      "heading": 20,
      "strength": 20,
      "stamina": 16,
      "handling": 16,
      "reflexes": 14
     }
    },
    {
     "name": "Bruno Renke",
     "num": 4,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 17,
      "finishing": 12,
      "tackling": 18,
      "heading": 20,
      "strength": 18,
      "stamina": 15,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Adem Glusac",
     "num": 6,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 14,
      "finishing": 9,
      "tackling": 20,
      "heading": 19,
      "strength": 16,
      "stamina": 16,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Bohdan Kovac",
     "num": 22,
     "pos": "RB",
     "qual": 14,
     "att": {
      "pace": 17,
      "technique": 15,
      "passing": 14,
      "finishing": 11,
      "tackling": 17,
      "heading": 15,
      "strength": 14,
      "stamina": 16,
      "handling": 16,
      "reflexes": 14
     }
    },
    {
     "name": "Mateus Osman",
     "num": 24,
     "pos": "LB",
     "qual": 15,
     "att": {
      "pace": 17,
      "technique": 16,
      "passing": 18,
      "finishing": 13,
      "tackling": 18,
      "heading": 14,
      "strength": 16,
      "stamina": 20,
      "handling": 15,
      "reflexes": 17
     }
    },
    {
     "name": "Ravi Lovren",
     "num": 16,
     "pos": "DM",
     "qual": 16,
     "att": {
      "pace": 16,
      "technique": 16,
      "passing": 19,
      "finishing": 12,
      "tackling": 19,
      "heading": 16,
      "strength": 20,
      "stamina": 20,
      "handling": 17,
      "reflexes": 16
     }
    },
    {
     "name": "Vuk Iric",
     "num": 8,
     "pos": "DM",
     "qual": 15,
     "att": {
      "pace": 16,
      "technique": 15,
      "passing": 17,
      "finishing": 12,
      "tackling": 19,
      "heading": 16,
      "strength": 16,
      "stamina": 18,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Tedy Polter",
     "num": 10,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 16,
      "passing": 14,
      "finishing": 11,
      "tackling": 12,
      "heading": 14,
      "strength": 14,
      "stamina": 16,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Ravi Velins",
     "num": 7,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 16,
      "passing": 16,
      "finishing": 13,
      "tackling": 14,
      "heading": 11,
      "strength": 12,
      "stamina": 16,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Ramon Marsh",
     "num": 14,
     "pos": "CM",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 17,
      "finishing": 14,
      "tackling": 13,
      "heading": 14,
      "strength": 13,
      "stamina": 16,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Adem Storm",
     "num": 20,
     "pos": "AM",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 16,
      "passing": 15,
      "finishing": 16,
      "tackling": 9,
      "heading": 10,
      "strength": 14,
      "stamina": 12,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Filip Osman",
     "num": 11,
     "pos": "AM",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 16,
      "passing": 14,
      "finishing": 16,
      "tackling": 12,
      "heading": 13,
      "strength": 14,
      "stamina": 14,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Ravil Hadzic",
     "num": 17,
     "pos": "RW",
     "qual": 13,
     "att": {
      "pace": 19,
      "technique": 17,
      "passing": 15,
      "finishing": 13,
      "tackling": 11,
      "heading": 10,
      "strength": 12,
      "stamina": 15,
      "handling": 15,
      "reflexes": 12
     }
    },
    {
     "name": "Davor Vrsaljko",
     "num": 23,
     "pos": "LW",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 14,
      "passing": 13,
      "finishing": 13,
      "tackling": 10,
      "heading": 9,
      "strength": 13,
      "stamina": 13,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Davor Salem",
     "num": 9,
     "pos": "ST",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 12,
      "passing": 13,
      "finishing": 19,
      "tackling": 10,
      "heading": 15,
      "strength": 13,
      "stamina": 15,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Sven Frank",
     "num": 19,
     "pos": "ST",
     "qual": 14,
     "att": {
      "pace": 17,
      "technique": 16,
      "passing": 15,
      "finishing": 19,
      "tackling": 11,
      "heading": 18,
      "strength": 14,
      "stamina": 16,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Ravil Brauer",
     "num": 18,
     "pos": "ST",
     "qual": 13,
     "att": {
      "pace": 17,
      "technique": 13,
      "passing": 11,
      "finishing": 19,
      "tackling": 9,
      "heading": 14,
      "strength": 15,
      "stamina": 15,
      "handling": 12,
      "reflexes": 13
     }
    }
   ]
  },
  {
   "name": "FC Korvane",
   "abbr": "KOR",
   "str": 78,
   "style": "New-money project",
   "color": "#0d6b4f",
   "squad": [
    {
     "name": "Borna Kraus",
     "num": 1,
     "pos": "GK",
     "qual": 16,
     "att": {
      "pace": 11,
      "technique": 15,
      "passing": 14,
      "finishing": 10,
      "tackling": 14,
      "heading": 18,
      "strength": 16,
      "stamina": 17,
      "handling": 20,
      "reflexes": 20
     }
    },
    {
     "name": "Viktor Korol",
     "num": 13,
     "pos": "GK",
     "qual": 15,
     "att": {
      "pace": 12,
      "technique": 16,
      "passing": 12,
      "finishing": 9,
      "tackling": 10,
      "heading": 14,
      "strength": 18,
      "stamina": 15,
      "handling": 18,
      "reflexes": 20
     }
    },
    {
     "name": "Edin Marsh",
     "num": 2,
     "pos": "RB",
     "qual": 16,
     "att": {
      "pace": 20,
      "technique": 16,
      "passing": 17,
      "finishing": 11,
      "tackling": 20,
      "heading": 17,
      "strength": 17,
      "stamina": 20,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Igor Marin",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 16,
      "finishing": 11,
      "tackling": 16,
      "heading": 14,
      "strength": 16,
      "stamina": 18,
      "handling": 13,
      "reflexes": 15
     }
    },
    {
     "name": "Hans Lovren",
     "num": 5,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 14,
      "finishing": 10,
      "tackling": 20,
      "heading": 18,
      "strength": 17,
      "stamina": 15,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Yannis Pinho",
     "num": 4,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 16,
      "finishing": 11,
      "tackling": 19,
      "heading": 20,
      "strength": 18,
      "stamina": 15,
      "handling": 14,
      "reflexes": 17
     }
    },
    {
     "name": "Matej Velins",
     "num": 6,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 12,
      "technique": 15,
      "passing": 16,
      "finishing": 12,
      "tackling": 19,
      "heading": 20,
      "strength": 20,
      "stamina": 14,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Kostas Marin",
     "num": 22,
     "pos": "RB",
     "qual": 15,
     "att": {
      "pace": 18,
      "technique": 16,
      "passing": 16,
      "finishing": 11,
      "tackling": 19,
      "heading": 14,
      "strength": 16,
      "stamina": 19,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Davor Horvat",
     "num": 24,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 17,
      "technique": 13,
      "passing": 16,
      "finishing": 11,
      "tackling": 15,
      "heading": 14,
      "strength": 13,
      "stamina": 16,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Otto Mraz",
     "num": 16,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 16,
      "passing": 16,
      "finishing": 12,
      "tackling": 17,
      "heading": 14,
      "strength": 15,
      "stamina": 15,
      "handling": 16,
      "reflexes": 15
     }
    },
    {
     "name": "Ramon Stoman",
     "num": 8,
     "pos": "DM",
     "qual": 15,
     "att": {
      "pace": 16,
      "technique": 17,
      "passing": 18,
      "finishing": 13,
      "tackling": 20,
      "heading": 16,
      "strength": 18,
      "stamina": 18,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Matej Ricci",
     "num": 10,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 15,
      "finishing": 11,
      "tackling": 11,
      "heading": 11,
      "strength": 11,
      "stamina": 13,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Bojan Vance",
     "num": 7,
     "pos": "CM",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 17,
      "passing": 15,
      "finishing": 13,
      "tackling": 13,
      "heading": 14,
      "strength": 12,
      "stamina": 15,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Andre Velins",
     "num": 14,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 14,
      "finishing": 10,
      "tackling": 13,
      "heading": 11,
      "strength": 11,
      "stamina": 14,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Ravil Lovren",
     "num": 20,
     "pos": "AM",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 18,
      "passing": 17,
      "finishing": 17,
      "tackling": 10,
      "heading": 10,
      "strength": 13,
      "stamina": 14,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Sam Marin",
     "num": 11,
     "pos": "AM",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 15,
      "passing": 14,
      "finishing": 15,
      "tackling": 12,
      "heading": 13,
      "strength": 14,
      "stamina": 12,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Adem Sengupta",
     "num": 17,
     "pos": "RW",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 16,
      "passing": 12,
      "finishing": 16,
      "tackling": 9,
      "heading": 11,
      "strength": 13,
      "stamina": 12,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Goran Brandt",
     "num": 23,
     "pos": "LW",
     "qual": 12,
     "att": {
      "pace": 17,
      "technique": 14,
      "passing": 12,
      "finishing": 12,
      "tackling": 8,
      "heading": 8,
      "strength": 11,
      "stamina": 13,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Lukas Ikonic",
     "num": 9,
     "pos": "ST",
     "qual": 13,
     "att": {
      "pace": 17,
      "technique": 13,
      "passing": 11,
      "finishing": 18,
      "tackling": 9,
      "heading": 16,
      "strength": 15,
      "stamina": 13,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Andre Sechin",
     "num": 19,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 11,
      "passing": 13,
      "finishing": 16,
      "tackling": 7,
      "heading": 16,
      "strength": 13,
      "stamina": 13,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Yuto Adamec",
     "num": 18,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 12,
      "passing": 11,
      "finishing": 15,
      "tackling": 9,
      "heading": 16,
      "strength": 14,
      "stamina": 14,
      "handling": 11,
      "reflexes": 13
     }
    }
   ]
  },
  {
   "name": "Iron Bresno",
   "abbr": "IRN",
   "str": 74,
   "style": "Pressing, fan-owned",
   "color": "#444",
   "squad": [
    {
     "name": "Pol Pinho",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 10,
      "finishing": 6,
      "tackling": 9,
      "heading": 13,
      "strength": 16,
      "stamina": 15,
      "handling": 17,
      "reflexes": 18
     }
    },
    {
     "name": "Felix Osman",
     "num": 13,
     "pos": "GK",
     "qual": 14,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 12,
      "finishing": 5,
      "tackling": 10,
      "heading": 14,
      "strength": 14,
      "stamina": 16,
      "handling": 19,
      "reflexes": 17
     }
    },
    {
     "name": "Luka Pavic",
     "num": 2,
     "pos": "RB",
     "qual": 15,
     "att": {
      "pace": 18,
      "technique": 17,
      "passing": 18,
      "finishing": 12,
      "tackling": 17,
      "heading": 13,
      "strength": 15,
      "stamina": 20,
      "handling": 16,
      "reflexes": 17
     }
    },
    {
     "name": "Drago Cruz",
     "num": 3,
     "pos": "LB",
     "qual": 15,
     "att": {
      "pace": 17,
      "technique": 16,
      "passing": 16,
      "finishing": 13,
      "tackling": 18,
      "heading": 16,
      "strength": 15,
      "stamina": 18,
      "handling": 14,
      "reflexes": 17
     }
    },
    {
     "name": "Viktor Bey",
     "num": 5,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 11,
      "passing": 15,
      "finishing": 7,
      "tackling": 19,
      "heading": 17,
      "strength": 16,
      "stamina": 12,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Stefan Holt",
     "num": 4,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 16,
      "finishing": 12,
      "tackling": 20,
      "heading": 18,
      "strength": 17,
      "stamina": 17,
      "handling": 17,
      "reflexes": 16
     }
    },
    {
     "name": "Marek Salem",
     "num": 6,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 14,
      "finishing": 7,
      "tackling": 16,
      "heading": 17,
      "strength": 18,
      "stamina": 15,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Marin Salas",
     "num": 22,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 17,
      "technique": 12,
      "passing": 16,
      "finishing": 11,
      "tackling": 14,
      "heading": 13,
      "strength": 13,
      "stamina": 16,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Otto Ricci",
     "num": 24,
     "pos": "LB",
     "qual": 15,
     "att": {
      "pace": 18,
      "technique": 14,
      "passing": 18,
      "finishing": 11,
      "tackling": 17,
      "heading": 13,
      "strength": 15,
      "stamina": 17,
      "handling": 14,
      "reflexes": 16
     }
    },
    {
     "name": "Emre Ricci",
     "num": 16,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 15,
      "passing": 16,
      "finishing": 12,
      "tackling": 17,
      "heading": 12,
      "strength": 17,
      "stamina": 17,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Kai Marin",
     "num": 8,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 18,
      "finishing": 10,
      "tackling": 18,
      "heading": 15,
      "strength": 15,
      "stamina": 18,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Aldo Saka",
     "num": 10,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 15,
      "passing": 13,
      "finishing": 9,
      "tackling": 10,
      "heading": 11,
      "strength": 11,
      "stamina": 13,
      "handling": 12,
      "reflexes": 10
     }
    },
    {
     "name": "Damir Holt",
     "num": 7,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 14,
      "finishing": 9,
      "tackling": 10,
      "heading": 11,
      "strength": 11,
      "stamina": 13,
      "handling": 10,
      "reflexes": 13
     }
    },
    {
     "name": "Bruno Bey",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 13,
      "finishing": 11,
      "tackling": 12,
      "heading": 9,
      "strength": 9,
      "stamina": 13,
      "handling": 9,
      "reflexes": 10
     }
    },
    {
     "name": "Uros Kovac",
     "num": 20,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 14,
      "passing": 13,
      "finishing": 14,
      "tackling": 10,
      "heading": 8,
      "strength": 10,
      "stamina": 11,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Sven Salem",
     "num": 11,
     "pos": "AM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 16,
      "finishing": 13,
      "tackling": 10,
      "heading": 12,
      "strength": 13,
      "stamina": 12,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Bruno Solak",
     "num": 17,
     "pos": "RW",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 11,
      "finishing": 14,
      "tackling": 11,
      "heading": 8,
      "strength": 13,
      "stamina": 14,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Bojan Frank",
     "num": 23,
     "pos": "LW",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 16,
      "passing": 12,
      "finishing": 13,
      "tackling": 8,
      "heading": 11,
      "strength": 11,
      "stamina": 12,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Ravi Lindqvist",
     "num": 9,
     "pos": "ST",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 14,
      "finishing": 18,
      "tackling": 10,
      "heading": 15,
      "strength": 13,
      "stamina": 15,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Igor Iric",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 10,
      "passing": 9,
      "finishing": 15,
      "tackling": 7,
      "heading": 13,
      "strength": 14,
      "stamina": 12,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Milos Berg",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 11,
      "finishing": 15,
      "tackling": 8,
      "heading": 13,
      "strength": 14,
      "stamina": 13,
      "handling": 12,
      "reflexes": 12
     }
    }
   ]
  },
  {
   "name": "Velkovic Eagles",
   "abbr": "VEL",
   "str": 72,
   "style": "Mountain fortress",
   "color": "#5a3a1a",
   "squad": [
    {
     "name": "Rok Iric",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 9,
      "technique": 13,
      "passing": 11,
      "finishing": 5,
      "tackling": 11,
      "heading": 12,
      "strength": 16,
      "stamina": 13,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Sami Ricci",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 8,
      "technique": 15,
      "passing": 13,
      "finishing": 4,
      "tackling": 11,
      "heading": 14,
      "strength": 16,
      "stamina": 15,
      "handling": 19,
      "reflexes": 18
     }
    },
    {
     "name": "Nils Mandzic",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 15,
      "finishing": 11,
      "tackling": 16,
      "heading": 11,
      "strength": 15,
      "stamina": 15,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Andrej Adamec",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 16,
      "passing": 16,
      "finishing": 9,
      "tackling": 16,
      "heading": 15,
      "strength": 14,
      "stamina": 18,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Drago Kallas",
     "num": 5,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 12,
      "finishing": 8,
      "tackling": 18,
      "heading": 16,
      "strength": 15,
      "stamina": 12,
      "handling": 15,
      "reflexes": 12
     }
    },
    {
     "name": "Ravi Marin",
     "num": 4,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 11,
      "passing": 12,
      "finishing": 9,
      "tackling": 18,
      "heading": 19,
      "strength": 18,
      "stamina": 12,
      "handling": 15,
      "reflexes": 12
     }
    },
    {
     "name": "Rok Severin",
     "num": 6,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 16,
      "finishing": 10,
      "tackling": 18,
      "heading": 19,
      "strength": 20,
      "stamina": 15,
      "handling": 16,
      "reflexes": 15
     }
    },
    {
     "name": "Sven Stoman",
     "num": 22,
     "pos": "RB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 14,
      "finishing": 12,
      "tackling": 15,
      "heading": 12,
      "strength": 14,
      "stamina": 18,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Karim Salas",
     "num": 24,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 17,
      "finishing": 9,
      "tackling": 15,
      "heading": 14,
      "strength": 16,
      "stamina": 18,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Ravil Kovac",
     "num": 16,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 15,
      "finishing": 12,
      "tackling": 17,
      "heading": 12,
      "strength": 16,
      "stamina": 17,
      "handling": 12,
      "reflexes": 15
     }
    },
    {
     "name": "Yuto Verde",
     "num": 8,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 15,
      "passing": 16,
      "finishing": 12,
      "tackling": 16,
      "heading": 13,
      "strength": 18,
      "stamina": 17,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Theo Vada",
     "num": 10,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 16,
      "finishing": 10,
      "tackling": 12,
      "heading": 12,
      "strength": 14,
      "stamina": 14,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Edin Kovac",
     "num": 7,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 14,
      "finishing": 9,
      "tackling": 12,
      "heading": 12,
      "strength": 12,
      "stamina": 15,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Bojan Tine",
     "num": 14,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 16,
      "finishing": 13,
      "tackling": 13,
      "heading": 14,
      "strength": 12,
      "stamina": 13,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Tomas Velins",
     "num": 20,
     "pos": "AM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 17,
      "passing": 13,
      "finishing": 13,
      "tackling": 10,
      "heading": 11,
      "strength": 11,
      "stamina": 12,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Pavel Soufiane",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 13,
      "finishing": 12,
      "tackling": 9,
      "heading": 8,
      "strength": 12,
      "stamina": 12,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Goran Frank",
     "num": 17,
     "pos": "RW",
     "qual": 12,
     "att": {
      "pace": 16,
      "technique": 15,
      "passing": 13,
      "finishing": 12,
      "tackling": 10,
      "heading": 8,
      "strength": 11,
      "stamina": 12,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Milos Tine",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 11,
      "finishing": 13,
      "tackling": 10,
      "heading": 7,
      "strength": 12,
      "stamina": 10,
      "handling": 13,
      "reflexes": 10
     }
    },
    {
     "name": "Borna Cruz",
     "num": 9,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 14,
      "passing": 13,
      "finishing": 16,
      "tackling": 7,
      "heading": 13,
      "strength": 15,
      "stamina": 14,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Borna Kovac",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 9,
      "finishing": 14,
      "tackling": 9,
      "heading": 15,
      "strength": 14,
      "stamina": 11,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Viktor Mandzic",
     "num": 18,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 12,
      "finishing": 17,
      "tackling": 10,
      "heading": 14,
      "strength": 14,
      "stamina": 14,
      "handling": 13,
      "reflexes": 13
     }
    }
   ]
  },
  {
   "name": "Port Vasska FC",
   "abbr": "VAS",
   "str": 70,
   "style": "Wealthy coastal",
   "color": "#1f5f8a",
   "squad": [
    {
     "name": "Davor Reuter",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 12,
      "passing": 12,
      "finishing": 7,
      "tackling": 9,
      "heading": 14,
      "strength": 15,
      "stamina": 15,
      "handling": 18,
      "reflexes": 19
     }
    },
    {
     "name": "Borna Vance",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 9,
      "technique": 15,
      "passing": 11,
      "finishing": 6,
      "tackling": 10,
      "heading": 13,
      "strength": 13,
      "stamina": 12,
      "handling": 18,
      "reflexes": 18
     }
    },
    {
     "name": "Drago Sengupta",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 14,
      "finishing": 9,
      "tackling": 15,
      "heading": 14,
      "strength": 12,
      "stamina": 16,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Drago Soufiane",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 13,
      "passing": 14,
      "finishing": 10,
      "tackling": 16,
      "heading": 13,
      "strength": 13,
      "stamina": 19,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Eros Renke",
     "num": 5,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 12,
      "passing": 15,
      "finishing": 10,
      "tackling": 18,
      "heading": 20,
      "strength": 18,
      "stamina": 13,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Borna Kovac",
     "num": 4,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 13,
      "finishing": 8,
      "tackling": 20,
      "heading": 20,
      "strength": 19,
      "stamina": 14,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Sven Vlasic",
     "num": 6,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 13,
      "finishing": 10,
      "tackling": 16,
      "heading": 18,
      "strength": 16,
      "stamina": 12,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Eli Sengupta",
     "num": 22,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 12,
      "passing": 14,
      "finishing": 9,
      "tackling": 16,
      "heading": 13,
      "strength": 13,
      "stamina": 17,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Felix Babic",
     "num": 24,
     "pos": "LB",
     "qual": 13,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 16,
      "finishing": 9,
      "tackling": 14,
      "heading": 14,
      "strength": 15,
      "stamina": 15,
      "handling": 15,
      "reflexes": 12
     }
    },
    {
     "name": "Matej Ricci",
     "num": 16,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 15,
      "finishing": 10,
      "tackling": 15,
      "heading": 12,
      "strength": 14,
      "stamina": 14,
      "handling": 15,
      "reflexes": 14
     }
    },
    {
     "name": "Theo Hadzic",
     "num": 8,
     "pos": "DM",
     "qual": 15,
     "att": {
      "pace": 16,
      "technique": 16,
      "passing": 18,
      "finishing": 14,
      "tackling": 17,
      "heading": 15,
      "strength": 18,
      "stamina": 17,
      "handling": 15,
      "reflexes": 17
     }
    },
    {
     "name": "Mateus Vance",
     "num": 10,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 11,
      "technique": 15,
      "passing": 14,
      "finishing": 13,
      "tackling": 11,
      "heading": 11,
      "strength": 13,
      "stamina": 14,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Sam Vance",
     "num": 7,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 12,
      "passing": 12,
      "finishing": 8,
      "tackling": 12,
      "heading": 9,
      "strength": 12,
      "stamina": 14,
      "handling": 10,
      "reflexes": 12
     }
    },
    {
     "name": "Ramon Dimitrov",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 10,
      "technique": 13,
      "passing": 12,
      "finishing": 11,
      "tackling": 12,
      "heading": 12,
      "strength": 12,
      "stamina": 14,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Dejan Batak",
     "num": 20,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 14,
      "passing": 13,
      "finishing": 12,
      "tackling": 7,
      "heading": 9,
      "strength": 10,
      "stamina": 12,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Goran Lume",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 14,
      "finishing": 13,
      "tackling": 8,
      "heading": 9,
      "strength": 10,
      "stamina": 11,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Ramon Dolny",
     "num": 17,
     "pos": "RW",
     "qual": 12,
     "att": {
      "pace": 16,
      "technique": 15,
      "passing": 13,
      "finishing": 12,
      "tackling": 11,
      "heading": 9,
      "strength": 13,
      "stamina": 13,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Petar Marin",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 17,
      "technique": 12,
      "passing": 13,
      "finishing": 11,
      "tackling": 7,
      "heading": 8,
      "strength": 11,
      "stamina": 10,
      "handling": 12,
      "reflexes": 10
     }
    },
    {
     "name": "Tin Dimitrov",
     "num": 9,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 11,
      "finishing": 14,
      "tackling": 7,
      "heading": 15,
      "strength": 12,
      "stamina": 12,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Ravil Lindqvist",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 10,
      "finishing": 17,
      "tackling": 8,
      "heading": 14,
      "strength": 12,
      "stamina": 13,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Pavel Briz",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 11,
      "passing": 10,
      "finishing": 15,
      "tackling": 7,
      "heading": 13,
      "strength": 11,
      "stamina": 12,
      "handling": 13,
      "reflexes": 13
     }
    }
   ]
  },
  {
   "name": "Red Star Olbrac",
   "abbr": "OLB",
   "str": 70,
   "style": "Military, physical",
   "color": "#8a1f1f",
   "squad": [
    {
     "name": "Igor Krol",
     "num": 1,
     "pos": "GK",
     "qual": 14,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 11,
      "finishing": 8,
      "tackling": 11,
      "heading": 16,
      "strength": 15,
      "stamina": 15,
      "handling": 20,
      "reflexes": 20
     }
    },
    {
     "name": "Marek Vlasic",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 10,
      "technique": 15,
      "passing": 11,
      "finishing": 7,
      "tackling": 9,
      "heading": 12,
      "strength": 14,
      "stamina": 13,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Viktor Krastev",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 17,
      "technique": 14,
      "passing": 13,
      "finishing": 11,
      "tackling": 14,
      "heading": 14,
      "strength": 13,
      "stamina": 16,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Beni Brauer",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 18,
      "technique": 13,
      "passing": 15,
      "finishing": 10,
      "tackling": 16,
      "heading": 13,
      "strength": 15,
      "stamina": 17,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Radek Severin",
     "num": 5,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 14,
      "finishing": 8,
      "tackling": 18,
      "heading": 19,
      "strength": 17,
      "stamina": 14,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Bohdan Novak",
     "num": 4,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 11,
      "passing": 13,
      "finishing": 7,
      "tackling": 17,
      "heading": 17,
      "strength": 17,
      "stamina": 13,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Bruno Brauer",
     "num": 6,
     "pos": "CB",
     "qual": 15,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 16,
      "finishing": 9,
      "tackling": 20,
      "heading": 20,
      "strength": 19,
      "stamina": 16,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Aldo Pelin",
     "num": 22,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 12,
      "passing": 14,
      "finishing": 11,
      "tackling": 15,
      "heading": 14,
      "strength": 15,
      "stamina": 17,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Ramon Polter",
     "num": 24,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 18,
      "technique": 14,
      "passing": 17,
      "finishing": 12,
      "tackling": 16,
      "heading": 14,
      "strength": 15,
      "stamina": 17,
      "handling": 16,
      "reflexes": 15
     }
    },
    {
     "name": "Ravi Pinho",
     "num": 16,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 16,
      "passing": 16,
      "finishing": 13,
      "tackling": 16,
      "heading": 15,
      "strength": 16,
      "stamina": 15,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Mateus Korol",
     "num": 8,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 16,
      "passing": 17,
      "finishing": 13,
      "tackling": 19,
      "heading": 15,
      "strength": 15,
      "stamina": 18,
      "handling": 16,
      "reflexes": 13
     }
    },
    {
     "name": "Omar Saka",
     "num": 10,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 10,
      "technique": 12,
      "passing": 13,
      "finishing": 8,
      "tackling": 12,
      "heading": 11,
      "strength": 11,
      "stamina": 12,
      "handling": 10,
      "reflexes": 12
     }
    },
    {
     "name": "Viktor Severin",
     "num": 7,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 10,
      "technique": 12,
      "passing": 13,
      "finishing": 8,
      "tackling": 9,
      "heading": 9,
      "strength": 9,
      "stamina": 14,
      "handling": 9,
      "reflexes": 10
     }
    },
    {
     "name": "Emre Marin",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 15,
      "finishing": 9,
      "tackling": 12,
      "heading": 9,
      "strength": 10,
      "stamina": 11,
      "handling": 9,
      "reflexes": 9
     }
    },
    {
     "name": "Mateus Vasic",
     "num": 20,
     "pos": "AM",
     "qual": 10,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 11,
      "finishing": 12,
      "tackling": 6,
      "heading": 8,
      "strength": 12,
      "stamina": 10,
      "handling": 9,
      "reflexes": 11
     }
    },
    {
     "name": "Milos Babic",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 15,
      "finishing": 12,
      "tackling": 8,
      "heading": 10,
      "strength": 10,
      "stamina": 13,
      "handling": 11,
      "reflexes": 10
     }
    },
    {
     "name": "Dario Kraus",
     "num": 17,
     "pos": "RW",
     "qual": 12,
     "att": {
      "pace": 18,
      "technique": 13,
      "passing": 12,
      "finishing": 15,
      "tackling": 10,
      "heading": 8,
      "strength": 12,
      "stamina": 11,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Andre Kallas",
     "num": 23,
     "pos": "LW",
     "qual": 12,
     "att": {
      "pace": 17,
      "technique": 16,
      "passing": 12,
      "finishing": 15,
      "tackling": 10,
      "heading": 11,
      "strength": 11,
      "stamina": 13,
      "handling": 11,
      "reflexes": 14
     }
    },
    {
     "name": "Sven Drekic",
     "num": 9,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 11,
      "passing": 12,
      "finishing": 15,
      "tackling": 9,
      "heading": 16,
      "strength": 13,
      "stamina": 11,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Bruno Krol",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 12,
      "finishing": 17,
      "tackling": 8,
      "heading": 15,
      "strength": 14,
      "stamina": 10,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Matej Berg",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 10,
      "passing": 12,
      "finishing": 14,
      "tackling": 9,
      "heading": 13,
      "strength": 14,
      "stamina": 13,
      "handling": 12,
      "reflexes": 11
     }
    }
   ]
  },
  {
   "name": "Athletic Navorda",
   "abbr": "NAV",
   "str": 68,
   "style": "Youth academy",
   "color": "#2a6a2a",
   "squad": [
    {
     "name": "Ilya Batak",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 10,
      "finishing": 4,
      "tackling": 10,
      "heading": 14,
      "strength": 16,
      "stamina": 14,
      "handling": 17,
      "reflexes": 17
     }
    },
    {
     "name": "Tin Reka",
     "num": 13,
     "pos": "GK",
     "qual": 12,
     "att": {
      "pace": 7,
      "technique": 11,
      "passing": 12,
      "finishing": 3,
      "tackling": 9,
      "heading": 13,
      "strength": 13,
      "stamina": 14,
      "handling": 18,
      "reflexes": 18
     }
    },
    {
     "name": "Goran Salas",
     "num": 2,
     "pos": "RB",
     "qual": 14,
     "att": {
      "pace": 18,
      "technique": 14,
      "passing": 16,
      "finishing": 9,
      "tackling": 16,
      "heading": 12,
      "strength": 16,
      "stamina": 19,
      "handling": 13,
      "reflexes": 15
     }
    },
    {
     "name": "Marek Reka",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 14,
      "passing": 16,
      "finishing": 9,
      "tackling": 18,
      "heading": 14,
      "strength": 16,
      "stamina": 18,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Davor Brauer",
     "num": 5,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 11,
      "passing": 13,
      "finishing": 10,
      "tackling": 17,
      "heading": 19,
      "strength": 18,
      "stamina": 13,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Viktor Oduya",
     "num": 4,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 15,
      "finishing": 8,
      "tackling": 20,
      "heading": 19,
      "strength": 17,
      "stamina": 16,
      "handling": 16,
      "reflexes": 15
     }
    },
    {
     "name": "Toby Sechin",
     "num": 6,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 15,
      "finishing": 9,
      "tackling": 18,
      "heading": 18,
      "strength": 18,
      "stamina": 16,
      "handling": 15,
      "reflexes": 15
     }
    },
    {
     "name": "Tomas Dolny",
     "num": 22,
     "pos": "RB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 17,
      "finishing": 10,
      "tackling": 15,
      "heading": 12,
      "strength": 13,
      "stamina": 16,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Karim Mori",
     "num": 24,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 15,
      "passing": 17,
      "finishing": 11,
      "tackling": 18,
      "heading": 13,
      "strength": 14,
      "stamina": 17,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Dario Wenger",
     "num": 16,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 18,
      "finishing": 11,
      "tackling": 16,
      "heading": 13,
      "strength": 17,
      "stamina": 18,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Pavel Wenger",
     "num": 8,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 14,
      "finishing": 12,
      "tackling": 17,
      "heading": 12,
      "strength": 16,
      "stamina": 14,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Ramon Berg",
     "num": 10,
     "pos": "CM",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 17,
      "finishing": 12,
      "tackling": 12,
      "heading": 12,
      "strength": 13,
      "stamina": 15,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Tedy Osman",
     "num": 7,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 13,
      "finishing": 8,
      "tackling": 12,
      "heading": 9,
      "strength": 12,
      "stamina": 13,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Aldo Glusac",
     "num": 14,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 13,
      "finishing": 9,
      "tackling": 13,
      "heading": 13,
      "strength": 13,
      "stamina": 12,
      "handling": 13,
      "reflexes": 10
     }
    },
    {
     "name": "Luka Korol",
     "num": 20,
     "pos": "AM",
     "qual": 10,
     "att": {
      "pace": 12,
      "technique": 14,
      "passing": 13,
      "finishing": 11,
      "tackling": 9,
      "heading": 9,
      "strength": 11,
      "stamina": 11,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Pol Kraus",
     "num": 11,
     "pos": "AM",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 15,
      "finishing": 13,
      "tackling": 8,
      "heading": 11,
      "strength": 13,
      "stamina": 12,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Sam Kuzma",
     "num": 17,
     "pos": "RW",
     "qual": 12,
     "att": {
      "pace": 18,
      "technique": 13,
      "passing": 13,
      "finishing": 12,
      "tackling": 10,
      "heading": 9,
      "strength": 13,
      "stamina": 11,
      "handling": 11,
      "reflexes": 14
     }
    },
    {
     "name": "Lev Mraz",
     "num": 23,
     "pos": "LW",
     "qual": 12,
     "att": {
      "pace": 16,
      "technique": 13,
      "passing": 11,
      "finishing": 12,
      "tackling": 9,
      "heading": 9,
      "strength": 13,
      "stamina": 11,
      "handling": 13,
      "reflexes": 11
     }
    },
    {
     "name": "Ilya Mandzic",
     "num": 9,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 11,
      "passing": 10,
      "finishing": 17,
      "tackling": 6,
      "heading": 12,
      "strength": 11,
      "stamina": 10,
      "handling": 11,
      "reflexes": 10
     }
    },
    {
     "name": "Sasha Paxon",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 9,
      "finishing": 16,
      "tackling": 7,
      "heading": 12,
      "strength": 14,
      "stamina": 12,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Bohdan Ricci",
     "num": 18,
     "pos": "ST",
     "qual": 12,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 10,
      "finishing": 18,
      "tackling": 8,
      "heading": 13,
      "strength": 12,
      "stamina": 14,
      "handling": 13,
      "reflexes": 12
     }
    }
   ]
  },
  {
   "name": "SC Gradelheim",
   "abbr": "GRA",
   "str": 66,
   "style": "Border intensity",
   "color": "#6a5a1a",
   "squad": [
    {
     "name": "Marin Iric",
     "num": 1,
     "pos": "GK",
     "qual": 14,
     "att": {
      "pace": 9,
      "technique": 13,
      "passing": 11,
      "finishing": 6,
      "tackling": 12,
      "heading": 15,
      "strength": 14,
      "stamina": 14,
      "handling": 17,
      "reflexes": 18
     }
    },
    {
     "name": "Marin Mraz",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 11,
      "finishing": 7,
      "tackling": 11,
      "heading": 14,
      "strength": 14,
      "stamina": 12,
      "handling": 18,
      "reflexes": 17
     }
    },
    {
     "name": "Andrej Vasco",
     "num": 2,
     "pos": "RB",
     "qual": 14,
     "att": {
      "pace": 15,
      "technique": 14,
      "passing": 15,
      "finishing": 12,
      "tackling": 15,
      "heading": 13,
      "strength": 16,
      "stamina": 17,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Uros Vasic",
     "num": 3,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 18,
      "technique": 13,
      "passing": 16,
      "finishing": 11,
      "tackling": 17,
      "heading": 15,
      "strength": 14,
      "stamina": 19,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Dejan Drekic",
     "num": 5,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 16,
      "finishing": 9,
      "tackling": 20,
      "heading": 17,
      "strength": 17,
      "stamina": 15,
      "handling": 14,
      "reflexes": 15
     }
    },
    {
     "name": "Marin Vance",
     "num": 4,
     "pos": "CB",
     "qual": 12,
     "att": {
      "pace": 9,
      "technique": 11,
      "passing": 13,
      "finishing": 6,
      "tackling": 18,
      "heading": 16,
      "strength": 16,
      "stamina": 13,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Bohdan Severin",
     "num": 6,
     "pos": "CB",
     "qual": 12,
     "att": {
      "pace": 9,
      "technique": 12,
      "passing": 11,
      "finishing": 9,
      "tackling": 17,
      "heading": 18,
      "strength": 15,
      "stamina": 11,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Remo Vasco",
     "num": 22,
     "pos": "RB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 12,
      "finishing": 10,
      "tackling": 13,
      "heading": 10,
      "strength": 13,
      "stamina": 16,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Luka Kallas",
     "num": 24,
     "pos": "LB",
     "qual": 14,
     "att": {
      "pace": 16,
      "technique": 15,
      "passing": 16,
      "finishing": 11,
      "tackling": 17,
      "heading": 14,
      "strength": 15,
      "stamina": 18,
      "handling": 15,
      "reflexes": 16
     }
    },
    {
     "name": "Ramon Horvat",
     "num": 16,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 15,
      "finishing": 11,
      "tackling": 18,
      "heading": 14,
      "strength": 17,
      "stamina": 16,
      "handling": 16,
      "reflexes": 14
     }
    },
    {
     "name": "Beni Reuter",
     "num": 8,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 16,
      "finishing": 10,
      "tackling": 16,
      "heading": 12,
      "strength": 15,
      "stamina": 17,
      "handling": 13,
      "reflexes": 15
     }
    },
    {
     "name": "Goran Verde",
     "num": 10,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 15,
      "finishing": 11,
      "tackling": 12,
      "heading": 12,
      "strength": 10,
      "stamina": 11,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Felix Mironov",
     "num": 7,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 16,
      "finishing": 10,
      "tackling": 10,
      "heading": 13,
      "strength": 13,
      "stamina": 14,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Karl Mori",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 10,
      "technique": 13,
      "passing": 14,
      "finishing": 9,
      "tackling": 12,
      "heading": 11,
      "strength": 11,
      "stamina": 14,
      "handling": 12,
      "reflexes": 10
     }
    },
    {
     "name": "Matej Iric",
     "num": 20,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 16,
      "passing": 15,
      "finishing": 13,
      "tackling": 8,
      "heading": 9,
      "strength": 11,
      "stamina": 11,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Ilya Babic",
     "num": 11,
     "pos": "AM",
     "qual": 9,
     "att": {
      "pace": 9,
      "technique": 13,
      "passing": 12,
      "finishing": 11,
      "tackling": 8,
      "heading": 7,
      "strength": 11,
      "stamina": 9,
      "handling": 9,
      "reflexes": 9
     }
    },
    {
     "name": "Karim Pinho",
     "num": 17,
     "pos": "RW",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 15,
      "passing": 13,
      "finishing": 14,
      "tackling": 7,
      "heading": 10,
      "strength": 10,
      "stamina": 10,
      "handling": 10,
      "reflexes": 11
     }
    },
    {
     "name": "Kostas Marsh",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 16,
      "technique": 14,
      "passing": 10,
      "finishing": 13,
      "tackling": 7,
      "heading": 9,
      "strength": 11,
      "stamina": 12,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Damir Novak",
     "num": 9,
     "pos": "ST",
     "qual": 10,
     "att": {
      "pace": 11,
      "technique": 11,
      "passing": 9,
      "finishing": 14,
      "tackling": 8,
      "heading": 14,
      "strength": 11,
      "stamina": 12,
      "handling": 11,
      "reflexes": 9
     }
    },
    {
     "name": "Stipe Korol",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 11,
      "finishing": 17,
      "tackling": 7,
      "heading": 13,
      "strength": 13,
      "stamina": 13,
      "handling": 13,
      "reflexes": 11
     }
    },
    {
     "name": "Ravi Marin",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 11,
      "passing": 9,
      "finishing": 16,
      "tackling": 8,
      "heading": 15,
      "strength": 14,
      "stamina": 10,
      "handling": 13,
      "reflexes": 10
     }
    }
   ]
  },
  {
   "name": "Lokomotiv Zreska",
   "abbr": "ZRE",
   "str": 65,
   "style": "Industrial grit",
   "color": "#7a4a1a",
   "squad": [
    {
     "name": "Milos Kuzma",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 8,
      "technique": 14,
      "passing": 13,
      "finishing": 6,
      "tackling": 10,
      "heading": 15,
      "strength": 13,
      "stamina": 12,
      "handling": 18,
      "reflexes": 18
     }
    },
    {
     "name": "Filip Vrsaljko",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 8,
      "technique": 15,
      "passing": 11,
      "finishing": 7,
      "tackling": 11,
      "heading": 15,
      "strength": 14,
      "stamina": 14,
      "handling": 19,
      "reflexes": 16
     }
    },
    {
     "name": "Drago Batak",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 16,
      "technique": 14,
      "passing": 14,
      "finishing": 8,
      "tackling": 14,
      "heading": 12,
      "strength": 14,
      "stamina": 17,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Lev Wenger",
     "num": 3,
     "pos": "LB",
     "qual": 12,
     "att": {
      "pace": 16,
      "technique": 12,
      "passing": 13,
      "finishing": 9,
      "tackling": 16,
      "heading": 12,
      "strength": 13,
      "stamina": 17,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Edin Reuter",
     "num": 5,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 12,
      "passing": 13,
      "finishing": 10,
      "tackling": 17,
      "heading": 19,
      "strength": 17,
      "stamina": 12,
      "handling": 14,
      "reflexes": 12
     }
    },
    {
     "name": "Emre Frank",
     "num": 4,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 12,
      "finishing": 7,
      "tackling": 18,
      "heading": 18,
      "strength": 17,
      "stamina": 15,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Andrej Vlasic",
     "num": 6,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 13,
      "technique": 11,
      "passing": 13,
      "finishing": 9,
      "tackling": 18,
      "heading": 18,
      "strength": 19,
      "stamina": 13,
      "handling": 13,
      "reflexes": 15
     }
    },
    {
     "name": "Filip Renke",
     "num": 22,
     "pos": "RB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 12,
      "finishing": 10,
      "tackling": 14,
      "heading": 13,
      "strength": 12,
      "stamina": 16,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Karim Saka",
     "num": 24,
     "pos": "LB",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 13,
      "finishing": 10,
      "tackling": 14,
      "heading": 14,
      "strength": 13,
      "stamina": 18,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Igor Mironov",
     "num": 16,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 12,
      "technique": 15,
      "passing": 17,
      "finishing": 11,
      "tackling": 16,
      "heading": 15,
      "strength": 16,
      "stamina": 15,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Lukas Kraus",
     "num": 8,
     "pos": "DM",
     "qual": 12,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 13,
      "finishing": 9,
      "tackling": 14,
      "heading": 14,
      "strength": 13,
      "stamina": 13,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Aldo Bey",
     "num": 10,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 14,
      "passing": 14,
      "finishing": 9,
      "tackling": 12,
      "heading": 9,
      "strength": 9,
      "stamina": 14,
      "handling": 10,
      "reflexes": 12
     }
    },
    {
     "name": "Emil Kovac",
     "num": 7,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 15,
      "passing": 14,
      "finishing": 11,
      "tackling": 12,
      "heading": 12,
      "strength": 11,
      "stamina": 13,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Petar Verde",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 12,
      "passing": 13,
      "finishing": 10,
      "tackling": 9,
      "heading": 11,
      "strength": 9,
      "stamina": 14,
      "handling": 11,
      "reflexes": 9
     }
    },
    {
     "name": "Hans Halil",
     "num": 20,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 13,
      "finishing": 15,
      "tackling": 7,
      "heading": 8,
      "strength": 13,
      "stamina": 10,
      "handling": 13,
      "reflexes": 10
     }
    },
    {
     "name": "Edin Iric",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 16,
      "passing": 13,
      "finishing": 14,
      "tackling": 7,
      "heading": 11,
      "strength": 12,
      "stamina": 12,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Eros Bey",
     "num": 17,
     "pos": "RW",
     "qual": 10,
     "att": {
      "pace": 16,
      "technique": 12,
      "passing": 9,
      "finishing": 11,
      "tackling": 9,
      "heading": 7,
      "strength": 8,
      "stamina": 11,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Niko Oduya",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 17,
      "technique": 13,
      "passing": 10,
      "finishing": 12,
      "tackling": 8,
      "heading": 7,
      "strength": 9,
      "stamina": 10,
      "handling": 13,
      "reflexes": 11
     }
    },
    {
     "name": "Radek Brandt",
     "num": 9,
     "pos": "ST",
     "qual": 10,
     "att": {
      "pace": 13,
      "technique": 9,
      "passing": 9,
      "finishing": 14,
      "tackling": 7,
      "heading": 13,
      "strength": 12,
      "stamina": 12,
      "handling": 12,
      "reflexes": 10
     }
    },
    {
     "name": "Emil Cole",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 10,
      "finishing": 14,
      "tackling": 8,
      "heading": 14,
      "strength": 11,
      "stamina": 13,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Petar Horvat",
     "num": 18,
     "pos": "ST",
     "qual": 9,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 7,
      "finishing": 15,
      "tackling": 7,
      "heading": 13,
      "strength": 10,
      "stamina": 10,
      "handling": 11,
      "reflexes": 11
     }
    }
   ]
  },
  {
   "name": "FK Dravona",
   "abbr": "DRA",
   "str": 64,
   "style": "Aggressive pressing",
   "color": "#4a2a6a",
   "squad": [
    {
     "name": "Rok Mironov",
     "num": 1,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 10,
      "finishing": 7,
      "tackling": 10,
      "heading": 12,
      "strength": 14,
      "stamina": 14,
      "handling": 16,
      "reflexes": 16
     }
    },
    {
     "name": "Stipe Sengupta",
     "num": 13,
     "pos": "GK",
     "qual": 12,
     "att": {
      "pace": 9,
      "technique": 12,
      "passing": 12,
      "finishing": 3,
      "tackling": 10,
      "heading": 11,
      "strength": 15,
      "stamina": 11,
      "handling": 15,
      "reflexes": 17
     }
    },
    {
     "name": "Eli Salem",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 13,
      "finishing": 11,
      "tackling": 17,
      "heading": 11,
      "strength": 13,
      "stamina": 17,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Tedy Ikonic",
     "num": 3,
     "pos": "LB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 15,
      "finishing": 10,
      "tackling": 14,
      "heading": 12,
      "strength": 14,
      "stamina": 17,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Sasha Krol",
     "num": 5,
     "pos": "CB",
     "qual": 12,
     "att": {
      "pace": 11,
      "technique": 10,
      "passing": 11,
      "finishing": 6,
      "tackling": 16,
      "heading": 18,
      "strength": 14,
      "stamina": 14,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Bojan Berg",
     "num": 4,
     "pos": "CB",
     "qual": 12,
     "att": {
      "pace": 11,
      "technique": 12,
      "passing": 13,
      "finishing": 8,
      "tackling": 16,
      "heading": 15,
      "strength": 16,
      "stamina": 14,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Filip Berg",
     "num": 6,
     "pos": "CB",
     "qual": 14,
     "att": {
      "pace": 11,
      "technique": 13,
      "passing": 15,
      "finishing": 8,
      "tackling": 18,
      "heading": 17,
      "strength": 19,
      "stamina": 16,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Uros Vasco",
     "num": 22,
     "pos": "RB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 15,
      "finishing": 10,
      "tackling": 14,
      "heading": 13,
      "strength": 12,
      "stamina": 17,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Ravi Brandt",
     "num": 24,
     "pos": "LB",
     "qual": 13,
     "att": {
      "pace": 17,
      "technique": 14,
      "passing": 13,
      "finishing": 10,
      "tackling": 16,
      "heading": 13,
      "strength": 14,
      "stamina": 15,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Nils Kallas",
     "num": 16,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 16,
      "finishing": 10,
      "tackling": 16,
      "heading": 14,
      "strength": 15,
      "stamina": 15,
      "handling": 12,
      "reflexes": 12
     }
    },
    {
     "name": "Aron Sechin",
     "num": 8,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 15,
      "passing": 16,
      "finishing": 12,
      "tackling": 16,
      "heading": 14,
      "strength": 16,
      "stamina": 16,
      "handling": 14,
      "reflexes": 14
     }
    },
    {
     "name": "Nils Polter",
     "num": 10,
     "pos": "CM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 14,
      "finishing": 9,
      "tackling": 10,
      "heading": 13,
      "strength": 13,
      "stamina": 15,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Viktor Ikonic",
     "num": 7,
     "pos": "CM",
     "qual": 9,
     "att": {
      "pace": 8,
      "technique": 13,
      "passing": 12,
      "finishing": 8,
      "tackling": 8,
      "heading": 10,
      "strength": 11,
      "stamina": 10,
      "handling": 10,
      "reflexes": 8
     }
    },
    {
     "name": "Stefan Novak",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 11,
      "technique": 14,
      "passing": 12,
      "finishing": 11,
      "tackling": 9,
      "heading": 11,
      "strength": 11,
      "stamina": 12,
      "handling": 10,
      "reflexes": 9
     }
    },
    {
     "name": "Vlado Mandzic",
     "num": 20,
     "pos": "AM",
     "qual": 9,
     "att": {
      "pace": 9,
      "technique": 11,
      "passing": 12,
      "finishing": 11,
      "tackling": 5,
      "heading": 8,
      "strength": 10,
      "stamina": 11,
      "handling": 10,
      "reflexes": 8
     }
    },
    {
     "name": "Filip Briz",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 13,
      "passing": 15,
      "finishing": 15,
      "tackling": 7,
      "heading": 8,
      "strength": 12,
      "stamina": 10,
      "handling": 11,
      "reflexes": 11
     }
    },
    {
     "name": "Kostas Osman",
     "num": 17,
     "pos": "RW",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 15,
      "passing": 10,
      "finishing": 12,
      "tackling": 8,
      "heading": 7,
      "strength": 12,
      "stamina": 13,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Borna Brandt",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 13,
      "passing": 13,
      "finishing": 14,
      "tackling": 7,
      "heading": 7,
      "strength": 12,
      "stamina": 12,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Karim Vasic",
     "num": 9,
     "pos": "ST",
     "qual": 10,
     "att": {
      "pace": 13,
      "technique": 9,
      "passing": 10,
      "finishing": 16,
      "tackling": 6,
      "heading": 13,
      "strength": 11,
      "stamina": 9,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Beni Cole",
     "num": 19,
     "pos": "ST",
     "qual": 10,
     "att": {
      "pace": 14,
      "technique": 10,
      "passing": 8,
      "finishing": 15,
      "tackling": 5,
      "heading": 12,
      "strength": 13,
      "stamina": 11,
      "handling": 9,
      "reflexes": 11
     }
    },
    {
     "name": "Sven Krol",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 12,
      "technique": 12,
      "passing": 10,
      "finishing": 17,
      "tackling": 8,
      "heading": 12,
      "strength": 13,
      "stamina": 13,
      "handling": 13,
      "reflexes": 12
     }
    }
   ]
  },
  {
   "name": "Dalnica Mariners",
   "abbr": "MAR",
   "str": 62,
   "style": "Cup giant-killers",
   "color": "#1a6a7a",
   "squad": [
    {
     "name": "Sasha Osman",
     "num": 1,
     "pos": "GK",
     "qual": 12,
     "att": {
      "pace": 7,
      "technique": 12,
      "passing": 12,
      "finishing": 5,
      "tackling": 8,
      "heading": 14,
      "strength": 13,
      "stamina": 13,
      "handling": 15,
      "reflexes": 17
     }
    },
    {
     "name": "Beni Vance",
     "num": 13,
     "pos": "GK",
     "qual": 13,
     "att": {
      "pace": 11,
      "technique": 12,
      "passing": 12,
      "finishing": 5,
      "tackling": 9,
      "heading": 13,
      "strength": 13,
      "stamina": 13,
      "handling": 19,
      "reflexes": 16
     }
    },
    {
     "name": "Toby Severin",
     "num": 2,
     "pos": "RB",
     "qual": 13,
     "att": {
      "pace": 14,
      "technique": 14,
      "passing": 15,
      "finishing": 11,
      "tackling": 16,
      "heading": 13,
      "strength": 12,
      "stamina": 16,
      "handling": 12,
      "reflexes": 15
     }
    },
    {
     "name": "Vuk Lume",
     "num": 3,
     "pos": "LB",
     "qual": 12,
     "att": {
      "pace": 14,
      "technique": 12,
      "passing": 15,
      "finishing": 7,
      "tackling": 16,
      "heading": 10,
      "strength": 14,
      "stamina": 17,
      "handling": 14,
      "reflexes": 13
     }
    },
    {
     "name": "Hans Babic",
     "num": 5,
     "pos": "CB",
     "qual": 12,
     "att": {
      "pace": 12,
      "technique": 11,
      "passing": 14,
      "finishing": 6,
      "tackling": 17,
      "heading": 18,
      "strength": 17,
      "stamina": 12,
      "handling": 13,
      "reflexes": 14
     }
    },
    {
     "name": "Vlado Briz",
     "num": 4,
     "pos": "CB",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 12,
      "passing": 14,
      "finishing": 8,
      "tackling": 17,
      "heading": 16,
      "strength": 16,
      "stamina": 14,
      "handling": 12,
      "reflexes": 14
     }
    },
    {
     "name": "Karl Paxon",
     "num": 6,
     "pos": "CB",
     "qual": 11,
     "att": {
      "pace": 10,
      "technique": 9,
      "passing": 13,
      "finishing": 7,
      "tackling": 16,
      "heading": 14,
      "strength": 13,
      "stamina": 12,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Janez Drekic",
     "num": 22,
     "pos": "RB",
     "qual": 12,
     "att": {
      "pace": 15,
      "technique": 11,
      "passing": 14,
      "finishing": 9,
      "tackling": 16,
      "heading": 10,
      "strength": 11,
      "stamina": 15,
      "handling": 13,
      "reflexes": 12
     }
    },
    {
     "name": "Janez Iric",
     "num": 24,
     "pos": "LB",
     "qual": 12,
     "att": {
      "pace": 16,
      "technique": 12,
      "passing": 13,
      "finishing": 10,
      "tackling": 15,
      "heading": 13,
      "strength": 14,
      "stamina": 15,
      "handling": 11,
      "reflexes": 12
     }
    },
    {
     "name": "Milos Kraus",
     "num": 16,
     "pos": "DM",
     "qual": 14,
     "att": {
      "pace": 12,
      "technique": 16,
      "passing": 15,
      "finishing": 13,
      "tackling": 16,
      "heading": 14,
      "strength": 16,
      "stamina": 16,
      "handling": 13,
      "reflexes": 15
     }
    },
    {
     "name": "Hans Oduya",
     "num": 8,
     "pos": "DM",
     "qual": 13,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 16,
      "finishing": 9,
      "tackling": 17,
      "heading": 13,
      "strength": 15,
      "stamina": 15,
      "handling": 15,
      "reflexes": 13
     }
    },
    {
     "name": "Sasha Vlasic",
     "num": 10,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 9,
      "technique": 12,
      "passing": 12,
      "finishing": 10,
      "tackling": 12,
      "heading": 12,
      "strength": 11,
      "stamina": 11,
      "handling": 10,
      "reflexes": 10
     }
    },
    {
     "name": "Joao Dimitrov",
     "num": 7,
     "pos": "CM",
     "qual": 9,
     "att": {
      "pace": 11,
      "technique": 10,
      "passing": 12,
      "finishing": 9,
      "tackling": 10,
      "heading": 10,
      "strength": 8,
      "stamina": 13,
      "handling": 8,
      "reflexes": 8
     }
    },
    {
     "name": "Lukas Velins",
     "num": 14,
     "pos": "CM",
     "qual": 10,
     "att": {
      "pace": 10,
      "technique": 14,
      "passing": 13,
      "finishing": 9,
      "tackling": 10,
      "heading": 12,
      "strength": 11,
      "stamina": 12,
      "handling": 9,
      "reflexes": 10
     }
    },
    {
     "name": "Radek Vada",
     "num": 20,
     "pos": "AM",
     "qual": 10,
     "att": {
      "pace": 11,
      "technique": 15,
      "passing": 13,
      "finishing": 11,
      "tackling": 8,
      "heading": 10,
      "strength": 12,
      "stamina": 9,
      "handling": 10,
      "reflexes": 9
     }
    },
    {
     "name": "Ravil Krastev",
     "num": 11,
     "pos": "AM",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 14,
      "passing": 13,
      "finishing": 15,
      "tackling": 9,
      "heading": 10,
      "strength": 13,
      "stamina": 12,
      "handling": 12,
      "reflexes": 13
     }
    },
    {
     "name": "Yannis Salem",
     "num": 17,
     "pos": "RW",
     "qual": 10,
     "att": {
      "pace": 13,
      "technique": 13,
      "passing": 10,
      "finishing": 11,
      "tackling": 7,
      "heading": 8,
      "strength": 11,
      "stamina": 12,
      "handling": 11,
      "reflexes": 9
     }
    },
    {
     "name": "Mateus Horvat",
     "num": 23,
     "pos": "LW",
     "qual": 11,
     "att": {
      "pace": 17,
      "technique": 14,
      "passing": 11,
      "finishing": 12,
      "tackling": 8,
      "heading": 7,
      "strength": 9,
      "stamina": 11,
      "handling": 13,
      "reflexes": 11
     }
    },
    {
     "name": "Felix Vasic",
     "num": 9,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 14,
      "technique": 13,
      "passing": 10,
      "finishing": 15,
      "tackling": 8,
      "heading": 12,
      "strength": 12,
      "stamina": 11,
      "handling": 11,
      "reflexes": 13
     }
    },
    {
     "name": "Borna Brauer",
     "num": 19,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 13,
      "technique": 12,
      "passing": 10,
      "finishing": 15,
      "tackling": 9,
      "heading": 14,
      "strength": 11,
      "stamina": 13,
      "handling": 13,
      "reflexes": 13
     }
    },
    {
     "name": "Matej Sechin",
     "num": 18,
     "pos": "ST",
     "qual": 11,
     "att": {
      "pace": 15,
      "technique": 11,
      "passing": 10,
      "finishing": 15,
      "tackling": 6,
      "heading": 14,
      "strength": 12,
      "stamina": 12,
      "handling": 11,
      "reflexes": 10
     }
    }
   ]
  }
 ]
};
if (typeof window!=='undefined') window.DALNIC = DALNIC;
if (typeof module!=='undefined') module.exports = DALNIC;
