// Dynamo Bresno first-team player data (read by player.html)
const PLAYERS = {

 "anton-varga": { name:"Anton Varga", role:"Head Coach", pos:"Manager", posFull:"Head Coach", nat:"Valrekian", age:48,
   trait:"pragmatic, fiercely protective",
   watch:"The new Executive Director will discover quickly how much interference Varga will tolerate before he simply walks.",
   bio:["Born in Bresno's industrial east, son of a factory shift leader and a seamstress, Varga learned the game on cracked asphalt where survival came before style. A respected midfielder for Lokomotiv Zreska and Union Dalnica and 27 times a Valrekian international, remembered for a 30-yard goal in a cup final against the capital.",
        "Dry, unapologetic and fiercely protective of his players, he made his name developing underdogs, famously dragging Red Star Polvan from the third tier to mid-table. Montiselle hired him because a local hero cannot be called a luxury puppet; his independence is the one thing they cannot quite control."],
   previous:"Lokomotiv Zreska, Union Dalnica (player) · Red Star Polvan (manager)" },

 "stefan-marusic": { attrs:["Quick reactions","Commands the box","Consistent"], name:"Stefan Marusic", num:1, pos:"Goalkeeper", posFull:"Goalkeeper", role:"Vice-Captain", nat:"Valrekian", age:30,
   trait:"commanding in the box",
   watch:"The arrival of Benno Kreutzer tests whether an untouchable No.1 is still quite so untouchable.",
   bio:["Dynamo's No.1 for six seasons: agile, dependable and at his best in the biggest games. Calm, disciplined and quietly superstitious, he leads the defensive unit as one of two vice-captains.",
        "Came through the famous Athletic Navorda academy before joining Dynamo at 21 for a nominal fee. A current Valrekian international and a family man, committed to the community work the club likes to photograph."],
   previous:"Athletic Navorda" },

 "filip-novak": { attrs:["Shot stopper","Strong penalty saver"], name:"Filip Novak", num:13, pos:"Goalkeeper", posFull:"Goalkeeper", nat:"Czech", age:33,
   trait:"penalty specialist",
   watch:"Slipping toward third choice, but a surprise cup hero, and a coach in waiting, may yet have his moment.",
   bio:["A positive, team-first veteran with an uncanny knack for saving penalties. He nurtures the emerging talent who will eventually take his place, and seems destined for the coaching staff.",
        "A well-travelled career took him from Brno and Slavia Prague through Italy and England before Dynamo offered a deal to transition from player to coach."],
   previous:"Brno, Slavia Prague, Ascoli, Genoa, Watford" },

 "benno-kreutzer": { attrs:["Exceptional reflexes","Quick to react"], name:"Benno Kreutzer", num:21, pos:"Goalkeeper", posFull:"Goalkeeper", nat:"German", age:20,
   trait:"quick reflexes, plays from the back",
   watch:"Impatient for minutes and prepared to undermine others to get them, though he is starting to learn the cost.",
   bio:["A confident, outspoken young keeper with sharp reflexes and the distribution to let his side play out from the back. Ambitious to a fault, and considering a loan for game time.",
        "It is rare for a player to leave Bayern Munich early; Kreutzer refused a new contract and engineered the move himself in summer 2026, in search of first-team football."],
   previous:"Bayern Munich" },

 "marco-signorelli": { attrs:["Flexible","Calm under pressure","Reads the game well"], name:"Marco Signorelli", num:2, pos:"Full-Back", posFull:"Right-Back / Left-Back", nat:"Italian", age:28,
   trait:"two-footed, versatile",
   watch:"Fighting to keep his place as Montiselle push for a younger, more marketable full-back, and weighing one last payday.",
   bio:["A former Milan prodigy who rebuilt a derailed career at Dynamo. Versatile and pragmatic, he can play either flank with either foot and simply gets on with the job.",
        "A bad debut injury and a change of manager froze him out at Milan; he found himself again at Cremonese and Lugano before arriving on a free in 2023/24."],
   previous:"AC Milan, Como, Sassuolo, Cremonese, Lugano" },

 "andriy-melnyk": { attrs:["Has pace","Accurate crosser"], name:"Andriy Melnyk", num:3, pos:"Left-Back", posFull:"Left-Back", nat:"Ukrainian", age:24,
   trait:"the team's strongest crosser",
   watch:"Torn between his contract and a deepening pull to go home and serve, believing he swapped duty for privilege.",
   bio:["An overlapping, attacking left-back with the most precise delivery in the squad. Patriotic and stoic, he carries a quiet guilt about the life he chose.",
        "A rising star at Shakhtar Donetsk when war broke out in 2022, he moved to Valrekia that summer, and has wrestled with the decision ever since."],
   previous:"Shakhtar Donetsk" },

 "omar-al-faraj": { attrs:["Calm under pressure","Plays out from the back"], name:"Omar Al-Faraj", num:4, pos:"Centre-Back", posFull:"Centre-Back", nat:"Saudi", age:23,
   trait:"physically dominant",
   watch:"A Montiselle marquee signing fighting the perception that he is a branding move rather than a footballer.",
   bio:["Image-conscious, ambitious and tech-obsessed, a physically commanding defender developed by the famous Al Shabab academy. Acceptance in the dressing room has not come easily.",
        "Normally bound for one of the Saudi royal family's big four, he was instead persuaded to join the Dynamo project, much to the royals' anger."],
   previous:"Al Shabab FC" },

 "viktor-kosa": { attrs:["Tough tackler","Dominant in the air","Formidable opponent"], name:"Viktor Kosa", num:5, pos:"Centre-Back", posFull:"Centre-Back", role:"Club Captain", nat:"Valrekian", age:32,
   trait:"hard tackler, old-school leader",
   watch:"His testimonial year, and an offer from rivals FC Korvane to become player-coach that he must answer.",
   bio:["Respected by the fans and feared by rivals: composed, stoic, and a leader whose few words carry weight. Ten years at the club this season, the captain on and off the pitch.",
        "A local boy from the railway town of Lokomotiv Zreska, he became one of Dynamo's first statement signings in their rise to dominance. Whether this is his final act in navy remains unsaid."],
   previous:"Lokomotiv Zreska" },

 "jacek-kowalski": { attrs:["Tireless engine","Exceptional stamina","Good at overlaps"], name:"Jacek Kowalski", num:14, pos:"Right-Back", posFull:"Right-Back", nat:"Polish", age:23,
   trait:"best one-on-one defender at the club",
   watch:"Rumours of homesickness and interest from Polish clubs that keep showing up in his form.",
   bio:["A tireless, overlapping full-back, humble and professional, with a defender's certainty that wingers rarely get past him.",
        "A Cracovia academy graduate and Poland youth international, bought to help push Dynamo on as a European side."],
   previous:"Cracovia" },

 "andrei-stoica": { attrs:["Adaptable","Can play across the back line","Reliable","Tough tackler"], name:"Andrei Stoica", num:15, pos:"Defender", posFull:"Right-Back / Left-Back / Centre-Back", nat:"Romanian", age:25,
   trait:"tough tackler, plays anywhere at the back",
   watch:"A recurring knee injury has management openly questioning whether he can sustain the top level.",
   bio:["A solid, taciturn utility defender who can fill any role across the back line and does not suffer fools. Known to bend a rule when it suits.",
        "Identified at Cluj as a squad player with potential, he joined in 2022/23, then a serious injury on debut stalled everything."],
   previous:"FC CFR 1907 Cluj" },

 "petar-simic": { attrs:["Dominant in the air","Strong","Leader"], name:"Petar Simic", num:20, pos:"Centre-Back", posFull:"Centre-Back", nat:"Croatian", age:34,
   trait:"dominant in the air",
   watch:"The legs are going. He mentors the younger defenders, and a scouting role feels close.",
   bio:["A patient, observant veteran and a commanding header of the ball, seeing out a long and distinguished career.",
        "From his home-town Osijek through Sweden, France and Belgium, he arrived on a free for one last chapter in navy. Now working towards his coaching badges, he is active in the Bresno Community Foundation's charity work."],
   previous:"NK Osijek, IFK Göteborg, RC Strasbourg, KRC Genk" },

 "nico-jovanovic": { attrs:["Calm","Leader","Focused"], name:"Nico Jovanovic", num:26, pos:"Centre-Back", posFull:"Centre-Back", nat:"Valrekian", age:18,
   trait:"ball-playing, future captain material",
   watch:"From a family of Iron Bresno supporters, and a loan to Iron is being discussed. Could he bridge the divide?",
   bio:["Calm, composed and elegant on the ball, a modern defender and a possible future captain the club want to bring through carefully.",
        "Still technically an academy development-squad player, he has already trained repeatedly with the first team and is being fast-tracked."],
   previous:"DB Academy" },

 "raul-sebastian": { attrs:["Reads the game well","Skilled at breaking up opponents attacks"], name:"Raul Sebastian", num:6, pos:"Defensive Mid", posFull:"Defensive Midfield", nat:"Argentinian", age:30,
   trait:"midfield destroyer",
   watch:"Framed for a nightclub brawl he didn't start, and quietly considering a move into coaching.",
   bio:["Wise and steady, a no-nonsense tough-tackler who rarely ventures forward and steadies everyone around him.",
        "A Vélez Sarsfield fan favourite who passed through Atlético Madrid and Marseille before a club-record move to Dynamo."],
   previous:"Vélez Sarsfield, Atlético Madrid, Marseille" },

 "liam-fitzroy": { attrs:["Never say die attitude","Relentless","Will do anything to win","Argues with the ref"], name:"Liam Fitzroy", num:8, pos:"Midfield", posFull:"Central / Attacking Midfield", nat:"English", age:27,
   nick:"Fitz", trait:"box-to-box",
   watch:"Alleged match-fixing links and gambling debts that follow him, and debt collectors who want him to throw games.",
   bio:["Charismatic and reckless, charming to some and toxic to others, a classic number eight who runs the midfield and lives for the night life.",
        "After a chaotic tour of English and Mediterranean football, a short-term Dynamo deal finally gave him a home. The question the club keeps asking: for how long?"],
   previous:"Leyton Orient, West Ham, Charlton, Fulham, Reading, Olympiacos, OFI Crete, Göztepe" },

 "martin-havel": { attrs:["Exceptional passing range","Reads the game well","Anticipates moves"], name:"Martin Havel", num:12, pos:"Midfield", posFull:"Central / Attacking Midfield", nat:"Valrekian", age:18,
   trait:"generational vision and first touch",
   watch:"The weight of a generation's hype, agents circling, and loyalty to the project pulling against lucrative offers abroad.",
   bio:["One of the most naturally gifted players in a generation: vision, touch and an eye for a pass others never see. Naive, eager, honest and diligent.",
        "He has led every age group through the academy, often playing above his years, and is mentored by Luka Petrovic. Can Dynamo keep hold of him?"],
   previous:"DB Academy" },

 "emil-kovac": { attrs:["Good engine","Team player","Vocal","Strong in the air"], name:"Emil Kovac", num:16, pos:"Defensive Mid", posFull:"Defensive Midfield", nat:"Valrekian", age:26,
   trait:"hard-working, strong in the air",
   watch:"Iron Bresno are courting him, pushing the line that Dynamo are forcing Valrekian players out for foreign stars.",
   bio:["Loyal and grounded, a tireless defensive midfielder who wins his headers and does the unseen work.",
        "Born in Valrekia to a Valrekian father and a Croatian mother, he moved to family in Croatia after his father's death and was forged in the Dinamo Zagreb academy. By way of Brøndby in Denmark, he was recruited back to Bresno as a homegrown option for European football."],
   previous:"GNK Dinamo Zagreb, Brøndby IF" },

 "stefano-toscano": { attrs:["Elegant playmaker","Plays defence splitting passes","Range of passing"], name:"Stefano Toscano", num:19, pos:"Deep Playmaker", posFull:"Defensive / Central Midfield", nick:"The Count", nat:"Italian", age:27,
   trait:"stylish range of passing",
   watch:"An agent pushing hard for one final move back to Serie A.",
   bio:["An intelligent, stylish deep-lying playmaker and a tactically astute reader of games: the quarterback who sets Dynamo's tempo.",
        "Forged in Parma's youth system during the club's collapse, he rebuilt at Como and arrived on a free chasing European football."],
   previous:"Parma, Como" },

 "rico-villalobos": { attrs:["Creative playmaker","Tricks","Good long shot"], name:"Rico Villalobos", num:22, pos:"Attacking Mid", posFull:"Attacking Midfield / Forward", nat:"Spanish", age:22,
   trait:"flair, can play false nine",
   watch:"A notorious entourage of three brothers and a high-profile romance that generate a steady stream of PR headaches.",
   bio:["A flashy, media-friendly creative spark who spends freely and flaunts it. In Spain, many wondered whether fashion or football came first.",
        "Came through the fabled Real Madrid academy without a first-team game, and was signed for a nominal fee."],
   previous:"Real Madrid, Real Madrid B, Racing de Santander" },

 "raul-ferreira": { attrs:["Exceptional range of passing","Resilient","Leader","Strong set piece taker"], name:"Raul Ferreira", num:35, pos:"Midfield", posFull:"Defensive / Central Midfield", nick:"The Heartbeat", nat:"Portuguese", age:29,
   trait:"free-kick taker, precision passer",
   watch:"Strong Montiselle social connections distract his form; CERCLE are rumoured to be circling for a future role.",
   bio:["Charismatic, cultured and occasionally hot-headed, the heartbeat of Dynamo's possession game and a player who can intimidate the youngsters.",
        "A Benfica graduate who sharpened his playmaking on loan at Alverca and Beira-Mar before breaking into the first team. An ill-fitting spell at Wolfsburg was rescued by a reputation-restoring move to Basel, where stellar European nights earned him a free transfer to drive Dynamo's continental campaign."],
   previous:"Benfica, Alverca (loan), Beira-Mar (loan), Wolfsburg, Basel" },

 "kenji-sato": { attrs:["Quick feet","Close control","Reads game well"], name:"Kenji Sato", num:38, pos:"Attacking Mid", posFull:"Attacking Midfield / Forward", nick:"Origami", nat:"Japanese", age:19,
   trait:"vision, glides past players",
   watch:"Language and cultural hurdles leave him exposed to manipulation, and make him a symbol of the club's reach into Asia.",
   bio:["A modern number ten with quick feet and incisive passing, nicknamed 'Origami' for the way he folds and unfolds a defence in a single move. Humble and polite, with an iron will to succeed abroad.",
        "An Osaka-born Cerezo academy product Montiselle see as the perfect bridge into a lucrative Japanese market."],
   previous:"Cerezo Osaka" },

 "farid-karam": { attrs:["Has pace to burn and bags of tricks"], name:"Farid Karam", num:7, pos:"Right Wing", posFull:"Right Wing", nat:"Libyan", age:26,
   trait:"the most tricks at the club",
   watch:"Clashes with the manager over defensive duties, and a reputation as a mercenary who will move the moment it suits him.",
   bio:["Fiery, vocal and an entertainer who lives to dazzle and be the centre of attention. Team-mates can tire of carrying him in hope of a single game-winning moment.",
        "A Benghazi hero at Al Ahly, he passed through Lyon and Hertha Berlin: the latter ended when he went on strike to force the Dynamo move."],
   previous:"Al Ahly, Lyon, Hertha Berlin" },

 "aleksandr-kovalenko": { attrs:["Pure muscle","Able to batter his way through any defence","Fighter"], name:"Aleksandr Kovalenko", num:9, pos:"Striker", posFull:"Striker", nick:"The Tank", nat:"Ukrainian", age:24,
   trait:"penalty taker, relentless presser",
   watch:"Training-ground bust-ups with anyone who won't match his intensity, and a friend in Melnyk he urges to stay.",
   bio:["A powerful, muscular forward and fierce competitor from a military family, calm under any pressure and the squad's hardest trainer in pursuit of perfection. His pace and first touch are not perfect, but relentless running and raw strength let him batter defenders into submission.",
        "A Dynamo Kyiv prodigy with one of the youngest league debuts on record, sold by Schalke when Dynamo came calling."],
   previous:"FC Dynamo Kyiv, FC Schalke 04" },

 "luka-petrovic": { attrs:["Great header of the ball","Hardworking","Handful for defenders"], name:"Luka Petrovic", num:10, pos:"Striker", posFull:"Striker", role:"Vice-Captain", nat:"Valrekian", age:28,
   trait:"target man, aerial threat",
   watch:"Playing through a long-term injury he is now downplaying; painkilling injections only last so long.",
   bio:["A one-club local hero, loyal and relentless, an old-fashioned target man who relies on strength, determination and maximum effort. He leads the offensive unit and mentors Martin Havel.",
        "Born and bred in Bresno and forged in the academy, he is synonymous with the club, which is exactly why the fans adore him."],
   previous:"DB Academy" },

 "nico-vanic": { attrs:["Lightning quick","Tight control of ball","Technically strong"], name:"Nico Vanic", num:11, pos:"Left Wing", posFull:"Left Wing", nat:"Valrekian", age:20,
   trait:"speed demon",
   watch:"Balancing his breakthrough with caring for a sick parent, and new Montiselle imports for competition.",
   bio:["A grounded, modest local flier with pace to burn, who holds the youth 100m record. The first touch still needs work, and he knows it.",
        "Born and bred in Bresno, he emerged as reserve player of the season before promotion to the first team."],
   previous:"DB Academy" },

 "tomas-varga": { attrs:["Dependable","Hardworking","Good crosser of the ball"], name:"Tomas Varga", num:17, pos:"Right Wing", posFull:"Right Wing", nat:"Valrekian", age:24,
   trait:"relentless runner, good crosser",
   watch:"Accusations of favouritism and nepotism as the manager's nephew.",
   bio:["Headstrong and defiant, a hard-working wideman who shields the ball and chases every lost cause, perhaps short of the attacking threat the position demands.",
        "He followed his uncle from club to club, joining Dynamo in summer 2026 for a nominal fee, and has had to work harder than most to silence the whispers."],
   previous:"Slovan Bratislava, Ferencváros, Rapid Vienna" },

 "lucas-brenner": { attrs:["Can play with either foot","Exceptional balance","Excellent close control","Long range shot specialist"], name:"Lucas Brenner", num:23, pos:"Winger", posFull:"Left / Right Wing", nat:"German", age:19,
   trait:"long-range 'worldie' goals",
   watch:"Struggling with fame after a viral goal brought him global attention, and left him vulnerable to exploitation.",
   bio:["An inside forward at ease on either foot and either wing, a specialist in spectacular long shots. Brilliant on his day, but he can go missing, and confidence is the battle.",
        "A Hamburg academy product who went viral at a youth tournament and was snapped up before a full season of men's football. He moved to Bresno with his family as a teenager, and is still finding his feet in Valrekia."],
   previous:"Hamburger SV" },

 "diego-barros": { attrs:["Exceptional dribbler","Flair player","Tricks"], name:"Diego Barros", num:24, pos:"Left Wing", posFull:"Left Wing", nat:"Brazilian", age:21,
   trait:"the ball sticks to his feet",
   watch:"Homesick and short of sunshine, with a complex third-party ownership deal blocking a route back to South America.",
   bio:["An emotional, passionate and supremely skilful dribbler: the ball seems glued to his boots.",
        "A São Paulo academy talent signed on a gamble in 2024 for a fee plus heavy add-ons and third-party ownership."],
   previous:"São Paulo FC" },

 "jean-luc-martenne": { attrs:["Strong dribbler","Good close control","Tricks","Good at free kicks"], name:"Jean-Luc Martenne", num:27, pos:"Forward", posFull:"Left / Right Wing / Striker", nat:"French", age:26,
   trait:"flamboyant, plays anywhere up front",
   watch:"A secret deal with a rival French fashion house threatens to make him a pawn in an off-field brand war with Montiselle.",
   bio:["A flamboyant dribbler and social-media star, well-groomed, suave and forever self-promoting. Traditionalists in the squad bristle at the sense of self before team.",
        "From Le Havre via Caen and Rennes, he chose Dynamo as a route into Europe's glitterati and the media glare Rennes could never offer."],
   previous:"Le Havre, SM Caen, Stade Rennes" },

 "emil-jorensen": { attrs:["Lightning fast reactions","Knack of being in the right place at the right time"], name:"Emil Jorensen", num:29, pos:"Striker", posFull:"Striker", nat:"Danish", age:22,
   trait:"fox in the box, quick reactions",
   watch:"Feels undervalued in the hierarchy, and has fallen under suspicion of leaking tactics and team news to journalists.",
   bio:["A sharp penalty-box poacher, competitive and fiery, with the quick reactions of a natural finisher.",
        "A Copenhagen forward who arrived on loan and was made permanent in the summer with Montiselle's backing, 